export const LOGIN = 'LOGIN';

export const ADD_MEMBER = 'ADD_MEMBER';
export const GET_MEMBER = 'GET_MEMBER';
export const  GET_ADMIN_PROFILE='GET_ADMIN_PROFILE';
export const  GET_ADMIN_TICKET='GET_ADMIN_TICKET';
export const ADD_ASSETS_CATEGORY = 'ADD_ASSETS_CATEGORY';
export const GET_ASSETS_CATEGORY = 'GET_ASSETS_CATEGORY';
export const DELETE_ASSETS_CATEGORY = 'DELETE_ASSETS_CATEGORY';
export const GET_ADMIN_ASSETS = 'GET_ADMIN_ASSETS';
export const GET_ADMIN_ASSETS_BY_ID = 'GET_ADMIN_ASSETS_BY_ID';

export const GET_MY_TICKET = 'GET_MY_TICKET';
export const ADD_MY_TICKET = 'ADD_MY_TICKET';


export const  GET_TECHNICIAN_TICKET='GET_TECHNICIAN_TICKET';
export const UPDATE_TICKET='UPDATE_TICKET';
export const  GET_TICKET_BY_ID='GET_TICKET_BY_ID';
export const  GET_TECHNICIAN_EMPLOYEE='GET_TECHNICIAN_EMPLOYEE';
export const  CHANGE_PASSWORD_TECHNICIAN='CHANGE_PASSWORD_TECHNICIAN';
export const  GET_TECHNICIAN_PROFILE='GET_TECHNICIAN_PROFILE';
export const  ADD_ASSETS_TECHNICIAN='ADD_ASSETS_TECHNICIAN';
export const  GET_ASSETS_TECHNICIAN='GET_ASSETS_TECHNICIAN';


export const  CHANGE_PASSWORD_EMPLOYEE='CHANGE_PASSWORD_EMPLOYEE';
export const  GET_EMPLOYEE_PROFILE='GET_EMPLOYEE_PROFILE';

export const  CHANGE_PASSWORD_STORE_KEEPER='CHANGE_PASSWORD_STORE_KEEPER';
export const  GET_STORE_KEEPER_PROFILE='GET_STORE_KEEPER_PROFILE';
export const ADD_ASSETS_CATEGORY_STORE = 'ADD_ASSETS_CATEGORY_STORE';
export const GET_ASSETS_CATEGORY_STORE = 'GET_ASSETS_CATEGORY_STORE';
export const ADD_ASSETS_STORE='ADD_ASSETS_STORE';
export const GET_ASSETS_STORE='GET_ASSETS_STORE';
export const UPDATE_ASSETS='UPDATE_ASSETS';
export const GET_ASSETS_BY_ID = 'GET_ASSETS_BY_ID';