export const LOGIN = 'LOGIN';

export const ADD_MEMBER = 'ADD_MEMBER';
export const GET_MEMBER = 'GET_MEMBER';
export const  GET_ADMIN_PROFILE='GET_ADMIN_PROFILE';
export const  GET_ADMIN_TICKET='GET_ADMIN_TICKET';
export const ADD_ASSETS_CATEGORY = 'ADD_ASSETS_CATEGORY';
export const GET_ASSETS_CATEGORY = 'GET_ASSETS_CATEGORY';
export const DELETE_ASSETS_CATEGORY = 'DELETE_ASSETS_CATEGORY';
export const GET_ADMIN_ASSETS = 'GET_ADMIN_ASSETS';
export const GET_ADMIN_ASSETS_BY_ID = 'GET_ADMIN_ASSETS_BY_ID';

export const GET_MY_TICKET = 'GET_MY_TICKET';
export const ADD_MY_TICKET = 'ADD_MY_TICKET';


export const  GET_TECHNICIAN_TICKET='GET_TECHNICIAN_TICKET';
export const UPDATE_TICKET='UPDATE_TICKET';
export const  GET_TICKET_BY_ID='GET_TICKET_BY_ID';
export const  GET_TECHNICIAN_EMPLOYEE='GET_TECHNICIAN_EMPLOYEE';
export const  CHANGE_PASSWORD_TECHNICIAN='CHANGE_PASSWORD_TECHNICIAN';
export const  GET_TECHNICIAN_PROFILE='GET_TECHNICIAN_PROFILE';
export const  ADD_ASSETS_TECHNICIAN='ADD_ASSETS_TECHNICIAN';
export const  GET_ASSETS_TECHNICIAN='GET_ASSETS_TECHNICIAN';
export const GET_ASSETS_CATEGORY_TECHNICIAN="GET_ASSETS_CATEGORY_TECHNICIAN";


export const  CHANGE_PASSWORD_EMPLOYEE='CHANGE_PASSWORD_EMPLOYEE';
export const  GET_EMPLOYEE_PROFILE='GET_EMPLOYEE_PROFILE';

export const  CHANGE_PASSWORD_STORE_KEEPER='CHANGE_PASSWORD_STORE_KEEPER';
export const  GET_STORE_KEEPER_PROFILE='GET_STORE_KEEPER_PROFILE';
export const ADD_ASSETS_CATEGORY_STORE = 'ADD_ASSETS_CATEGORY_STORE';
export const GET_ASSETS_CATEGORY_STORE = 'GET_ASSETS_CATEGORY_STORE';
export const ADD_ASSETS_STORE='ADD_ASSETS_STORE';
export const GET_ASSETS_STORE='GET_ASSETS_STORE';
export const UPDATE_ASSETS='UPDATE_ASSETS';
export const GET_ASSETS_BY_ID = 'GET_ASSETS_BY_ID';

export const  GET_EMPLOYEE_TICKET_BY_ID='GET_EMPLOYEE_TICKET_BY_ID';
export const  GET_ADMIN_TICKET_BY_ID='GET_ADMIN_TICKET_BY_ID';
export const UPDATE_MEMBER='UPDATE_MEMBER';
export const  GET_MEMBER_BY_ID='GET_MEMBER_BY_ID';
export const UPDATE_ADMIN_ASSETS='UPDATE_ADMIN_ASSETS';
export const  GET_ASSIGN_ASSETS='GET_ASSIGN_ASSETS';
export const UPDATE_ADMIN_ASSETS_CATEGORY='UPDATE_ADMIN_ASSETS_CATEGORY';

export const GET_DASHBOARD_EMPLOYEE_CLOSE='GET_DASHBOARD_EMPLOYEE_CLOSE';
export const GET_DASHBOARD_EMPLOYEE_OPEN='GET_DASHBOARD_EMPLOYEE_OPEN';
export const GET_DASHBOARD_EMPLOYEE_ASSET='GET_DASHBOARD_EMPLOYEE_ASSET';
export const GET_DASHBOARD_EMPLOYEE_CATEGORY='GET_DASHBOARD_EMPLOYEE_CATEGORY';

export const GET_DASHBOARD_TECHNICIAN_CLOSE='GET_DASHBOARD_TECHNICIAN_CLOSE';
export const GET_DASHBOARD_TECHNICIAN_OPEN='GET_DASHBOARD_TECHNICIAN_OPEN';
export const GET_DASHBOARD_TECHNICIAN_TICKET='GET_DASHBOARD_TECHNICIAN_TICKET';

export const GET_TOTAL_ASSET='GET_TOTAL_ASSET';
export const GET_TOTAL_CATEGORY='GET_TOTAL_CATEGORY';
export const GET_TOTAL_EMPLOYEE='GET_TOTAL_EMPLOYEE';
export const GET_TOTAL_MEMBER='GET_TOTAL_MEMBER';

export const UPDATE_EMPLOYEE_PROFILE='UPDATE_EMPLOYEE_PROFILE';
export const UPDATE_TECHNICIAN_PROFILE='UPDATE_TECHNICIAN_PROFILE';
export const UPDATE_STOREKEEPER_PROFILE='UPDATE_STOREKEEPER_PROFILE';

export const GET_STORE_TOTAL_ASSET='GET_STORE_TOTAL_ASSET';
export const GET_STORE_TOTAL_CATEGORY='GET_STORE_TOTAL_CATEGORY';
export const GET_STORE_TOTAL_MEMBER='GET_STORE_TOTAL_MEMBER';

export const UPDATE_STORE_ASSETS_CATEGORY='UPDATE_STORE_ASSETS_CATEGORY';

export const GET_EMPLOYEE_ASSETS='GET_EMPLOYEE_ASSETS';

export const LOGOUT_STORE='LOGOUT_STORE';
export const LOGOUT_ADMIN='LOGOUT_ADMIN';
export const LOGOUT_EMPLOYEE='LOGOUT_EMPLOYEE';
export const LOGOUT_TECHNICIAN='LOGOUT_TECHNICIAN';